apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sip-api
  namespace: sip-phone
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/websocket-services: "sip-api"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - sip-api.nexvision.cc
    secretName: sip-api-tls
  rules:
  - host: sip-api.nexvision.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sip-api
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sip-ws
  namespace: sip-phone
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/websocket-services: "asterisk"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - sip-ws.nexvision.cc
    secretName: sip-ws-tls
  rules:
  - host: sip-ws.nexvision.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: asterisk
            port:
              number: 8080
